import React from "react";
import "../css/feedback.css";
import framer from "../images/framer.png";
import ghost from "../images/ghost.png";
import amazon from "../images/amazon.png";
import basecamp from "../images/basecamp.png";
import pipedrive from "../images/pipedrive.png";

const Feedback = () => {
  return (
    <div className="container feedback">
      <h2>Client’s Feedback</h2>
      <marquee behavior="" direction="">
        <div className="feedback-marquee">
          <div className="cards">
            <div className="card-body">
              <h5 className="cardtitle">Advanced Systems</h5>
              <p className="cardtext">
                'm a data junkie, and I've tried countless <br /> analytics
                websites over the years. But this <br /> website is easily one
                of the best I've come <br /> across. The analytics are
                comprehensive <br />
                and detailed, and the platform is easy to <br /> use. I've
                recommended it to all.
              </p>
              <p className="cardname">Benjamin Clay</p>
              <p className="cardcompany">Jason Moore LLC</p>
            </div>
          </div>

          <div className="cards">
            <div className="card-body">
              <h5 className="cardtitle">Easy to Use</h5>
              <p className="cardtext">
                "As a small business owner, I have struggled <br /> to make
                sense of the data generated by my <br /> website. But this
                analytics website has been <br /> a game- changer for me. The
                metrics are <br /> presented in a clear and concise manner,
              </p>
              <p className="cardname">Olivia Denver</p>
              <p className="cardcompany">The AI Formation</p>
            </div>
          </div>

          <div className="cards">
            <div className="card-body">
              <h5 className="cardtitle">Best UI</h5>
              <p className="cardtext">
                I love how easy it is to use this website. <br /> Even as
                someone who is not particularly <br /> tech-savvy, I was able to
                navigate it with <br /> ease. The analytics provided are <br />
                comprehensive and insightful,
              </p>
              <p className="cardname">Peter Morgan</p>
              <p className="cardcompany">Sans Forms </p>
            </div>
          </div>

          <div className="cards">
            <div className="card-body">
              <h5 className="cardtitle">Exceptional !</h5>
              <p className="cardtext">
                I stumbled upon this tool and was blown <br /> away by the
                analytics and insights it <br /> provided. The interface is
                user-friendly, and <br /> the data is presented in a visually
                appealing <br /> way. Highly recommend giving it a try!"
              </p>
              <p className="cardname">Jason Moritz</p>
              <p className="cardcompany">The USA Tech</p>
            </div>
          </div>
        </div>
      </marquee>
      <p className="feedback-para">
        Scaling the world's best and biggest companies
      </p>
      <div className="feedback-logos">
        <img src={framer} alt="" />
        <img src={pipedrive} alt="" />
        <img src={ghost} alt="" />
        <img src={amazon} alt="" />
        <img src={basecamp} alt="" />
      </div>
    </div>
  );
};

export default Feedback;
